
```{r}
library(targets)
library(dplyr)
library(tidymodels)
library(xgboost)
library(modeltime)
library(tidyverse)
library(lubridate)
library(timetk)
library(dplyr)
```


```{r}
ww_cdc_raw |> 
    #Filter for Cook County cases sampled at Wastewater Treatment Plants
    filter(grepl("17031", county_names) & sample_location == "wwtp")|>
    group_by(wwtp_name, sample_collect_date, major_lab_method, population_served) |>
    summarize(
        across(
            c(flow_rate, pcr_target_avg_conc),
            mean
        ),
        .groups = "keep"
    ) |> 
    ungroup() |> 
    mutate(
        short_name = 
            case_when(
                grepl("kirie", wwtp_name) ~ "kirie",
                grepl("egan", wwtp_name) ~ "egan",
                grepl("hanover", wwtp_name) ~ "hanover",
                grepl("brien", wwtp_name) ~ "obrien",
                grepl(" sws", wwtp_name) ~ "stickney 1",
                grepl(" ws", wwtp_name) ~ "stickney 2",
                grepl("lemont", wwtp_name) ~ "lemont",
                grepl("calumet", wwtp_name) ~ "calumet"
            ),
        display_name = 
            case_when(
                grepl("kirie", wwtp_name) ~ "Kirie, Mid Northwest Suburbs",
                grepl("egan", wwtp_name) ~ "Egan, Far Northwest Suburbs",
                grepl("hanover", wwtp_name) ~ "Hanover Park, Far Northwest Suburbs",
                grepl("brien", wwtp_name) ~ "O'Brien, Northeast Suburbs and Chicago",
                grepl(" sws", wwtp_name) ~ "Stickney (1), West Suburbs and Chicago",
                grepl(" ws", wwtp_name) ~ "Stickney (2), West Suburbs and Chicago",
                grepl("lemont", wwtp_name) ~ "Lemont, Far Southwest Suburbs",
                grepl("calumet", wwtp_name) ~ "Calumet, South Suburbs and Chicago"
            ),
        .after = wwtp_name
    ) |> 
    mutate(
        flow_rate_l = flow_rate * 3.785411784, #convert flow_rate to liters
        conc_flowrt = pcr_target_avg_conc * flow_rate_l
    ) |> 
    arrange(sample_collect_date) |> 
    view()
    
lemont_adjust_dates <- 
  ww_cook |>
  filter(short_name %in% c("kirie", "egan", "hanover")) |>
  group_by(date) |>
  tally() |>
  ungroup() |>
  mutate(date = date + 1) |>
  pull(date)
    
```


```{r}
timetk::plot_time_series(
    .data = tar_read(biobot_cases_in_cook),
    .date_var = date,
    .value = rolling_average_cases_per_100k_centered
)
```

```{r}
split_biobot_cases_in_cook <- 
    tar_read(biobot_cases_in_cook) |> 
    rsample::initial_time_split()
```

```{r}
model_fit_arima_no_boost <- 
    arima_reg() |>
    set_engine(engine = "auto_arima") |>
    fit(rolling_average_cases_per_100k_centered ~ date, data = training(split_biobot_cases_in_cook))
```

```{r}
model_fit_arima_boosted <- 
    arima_boost(
        min_n = 2,
        learn_rate = 0.015
    ) |>
    set_engine(engine = "auto_arima_xgboost") |>
    fit(value ~ date + as.numeric(date) + factor(month(date, label = TRUE), ordered = F),
        data = training(splits))
```

